# This starter workflow is for a CMake project running on a single platform. There is a different starter workflow if you need cross-platform coverage.
# See: https://github.com/actions/starter-workflows/blob/main/ci/cmake-multi-platform.yml
name: CMake on a single platform

on:
  push:
    branches: [ "devel" ]
  pull_request:
    branches: [ "devel" ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    # The CMake configure and build commands are platform agnostic and should work equally well on Windows or Mac.
    # You can convert this to a matrix build if you need cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: self-hosted
    env:
      CPPUNIT_IGNORE: >-
        class CppUnit::TestCaller<class PathTest>.testFind,
        class CppUnit::TestCaller<class ICMPSocketTest>.testSendToReceiveFrom,
        class CppUnit::TestCaller<class ICMPClientTest>.testPing,
        class CppUnit::TestCaller<class ICMPClientTest>.testBigPing,
        class CppUnit::TestCaller<class ICMPSocketTest>.testMTU,
        class CppUnit::TestCaller<class HTTPSClientSessionTest>.testProxy,
        class CppUnit::TestCaller<class HTTPSStreamFactoryTest>.testProxy
    steps:
      - uses: actions/checkout@v4
      - run: cmake -S. -Bcmake-build -DENABLE_NETSSL_WIN=ON -DENABLE_NETSSL=OFF -DENABLE_CRYPTO=OFF -DENABLE_JWT=OFF -DENABLE_DATA=ON -DENABLE_DATA_ODBC=ON -DENABLE_DATA_MYSQL=OFF -DENABLE_DATA_POSTGRESQL=OFF -DENABLE_TESTS=ON
      - run: cmake --build cmake-build --config Release
      - uses: ./.github/actions/retry-action
        with:
          timeout_minutes: 90
          max_attempts: 3
          retry_on: any
          command: >-
            cd cmake-build;
            ctest --output-on-failure -E "(DataMySQL)|(DataODBC)|(Redis)|(MongoDB)" -C Release

